name: Build Test # Github Action 페이지 좌측 리스트에 표시될 이름
on:
  push:
    branches: [develop, feature/**]
    paths:
      - apps/front/**
      - packages/**
      - .github/workflows/**
      - package.json
      - pnpm-lock.yaml
      - turbo.json
      - tsconfig.json
  pull_request:
    branches:
      - "*"

jobs:
  node-build-test:
    name: Node Build Test
    strategy:
      matrix:
        type: ["front", "server"]
    uses: ./.github/workflows/node-build-reuseable.yaml
    with:
      type: ${{ matrix.type }}

  docker-build-test:
    name: Docker Build Test
    needs: [node-build-test]
    strategy:
      matrix:
        type: ["front", "server"]
    uses: ./.github/workflows/docker-build-reuseable.yaml
    with:
      type: ${{ matrix.type }}
      push: false
