name: Build Test # Github Action 페이지 좌측 리스트에 표시될 이름
on:
  push:
    branches: [develop, feature/**]
    paths:
      - apps/front/**
      - packages/**
      - .github/workflows/**
      - package.json
      - pnpm-lock.yaml
      - turbo.json
      - tsconfig.json
  pull_request:
    branches:
      - "*"

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ["front", "server"]
    steps:
      # Checkout Repository
      - name: Check out source code
        uses: actions/checkout@v2.1.0

      - uses: ./.github/workflows/node-build-reuseable.yaml
        with:
          type: ${{ matrix.type }}

      - uses: ./.github/workflows/docker-build-reuseable.yaml
        with:
          type: ${{ matrix.type }}
          push: false
