name: Build Test # Github Action 페이지 좌측 리스트에 표시될 이름
on:
  push:
    branches: [develop, feature/**]
    paths:
      - apps/front/**
      - packages/**
      - .github/workflows/**
      - package.json
      - pnpm-lock.yaml
      - turbo.json
      - tsconfig.json
  pull_request:
    branches:
      - "*"

jobs:
  # Build Apps
  front-build-test:
    name: Front Build Test
    secrets: inherit
    uses: ./.github/workflows/node-build-reuseable.yaml
    with:
      type: front
      env: production

  server-build-test:
    name: Server Build Test
    secrets: inherit
    uses: ./.github/workflows/node-build-reuseable.yaml
    with:
      type: server
      env: production

  # Deploy Apps
  front-docker-build:
    name: Front Docker Build Test
    needs: [front-build-test]
    secrets: inherit
    uses: ./.github/workflows/docker-build-reuseable.yaml
    with:
      type: front
      env: production
      push: true

  server-docker-build:
    name: Server Docker Build Test
    needs: [server-build-test]
    secrets: inherit
    uses: ./.github/workflows/docker-build-reuseable.yaml
    with:
      type: server
      env: production
      push: true
